sudo: required
language: minimal
services:
  - docker

before_install:
  - docker build -t srodge1/docker-react -f Dockerfile.dev .

script:
  - docker run srodge1/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $aws_access_key
  secret_access_key:
    secure: $aws_secret_key
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-295593811365
  bucket_path: docker-react
  on:
    branch: master
